inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - "vendor/**/*"
    - "db/schema.rb"
    - "node_modules/**/*"
    - "tmp/**/*"
    - ".git/**/*"
    - "db/**/*"
    - "config/**/*"
    - "bin/*"
  DisplayCopNames: true
  NewCops: enable
  
  
# クラスのコメント必須を無視
Documentation:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

# 文字リテラルのイミュータブル宣言を無視（freezeになるのはRuby3以降）
Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

# 日本語のコメントを許可する
Style/AsciiComments:
  Enabled: false
