default: &default
  adapter: mysql2
  encoding: utf8
  database: portfolio
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.db[:username] %>
  password: <%= Rails.application.credentials.db[:password] %>
  socket: /var/lib/mysql/mysql.sock
  host: localhost
  timeout: 5000
  

development:
  <<: *default
  
test:
  <<: *default

production:
  <<: *default
  
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>